# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Infrared_Thermal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 870)
        MainWindow.setStyleSheet("background-color: rgb(131, 255, 224);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Frame_BtnBar = QtWidgets.QFrame(self.centralwidget)
        self.Frame_BtnBar.setGeometry(QtCore.QRect(40, 70, 221, 761))
        self.Frame_BtnBar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px")
        self.Frame_BtnBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_BtnBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_BtnBar.setObjectName("Frame_BtnBar")
        self.Button_ShotOne = QtWidgets.QPushButton(self.Frame_BtnBar)
        self.Button_ShotOne.setGeometry(QtCore.QRect(20, 270, 161, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ShotOne.setFont(font)
        self.Button_ShotOne.setStyleSheet("color: rgb(63, 63, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px\n"
"")
        self.Button_ShotOne.setObjectName("Button_ShotOne")
        self.Button_ShotStop = QtWidgets.QPushButton(self.Frame_BtnBar)
        self.Button_ShotStop.setGeometry(QtCore.QRect(20, 190, 161, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ShotStop.setFont(font)
        self.Button_ShotStop.setStyleSheet("color: rgb(63, 63, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px\n"
"")
        self.Button_ShotStop.setObjectName("Button_ShotStop")
        self.Button_Settings = QtWidgets.QPushButton(self.Frame_BtnBar)
        self.Button_Settings.setGeometry(QtCore.QRect(20, 360, 161, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Settings.setFont(font)
        self.Button_Settings.setStyleSheet("color: rgb(63, 63, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px\n"
"")
        self.Button_Settings.setObjectName("Button_Settings")
        self.Button_ShotBegin = QtWidgets.QPushButton(self.Frame_BtnBar)
        self.Button_ShotBegin.setGeometry(QtCore.QRect(20, 160, 161, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ShotBegin.setFont(font)
        self.Button_ShotBegin.setStyleSheet("color: rgb(63, 63, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px\n"
"")
        self.Button_ShotBegin.setObjectName("Button_ShotBegin")
        self.Button_Quit = QtWidgets.QPushButton(self.Frame_BtnBar)
        self.Button_Quit.setGeometry(QtCore.QRect(20, 400, 161, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Quit.setFont(font)
        self.Button_Quit.setStyleSheet("color: rgb(63, 63, 63);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:5px\n"
"")
        self.Button_Quit.setObjectName("Button_Quit")
        self.label_2 = QtWidgets.QLabel(self.Frame_BtnBar)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.Frame_BtnBar)
        self.line.setGeometry(QtCore.QRect(50, 110, 118, 3))
        self.line.setStyleSheet("background-color: rgb(69, 195, 174);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Frame_VideoFrame = QtWidgets.QFrame(self.centralwidget)
        self.Frame_VideoFrame.setGeometry(QtCore.QRect(280, 70, 881, 771))
        self.Frame_VideoFrame.setStyleSheet("\n"
"background-color: rgb(205, 255, 241);\n"
"border-radius:25px")
        self.Frame_VideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_VideoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_VideoFrame.setObjectName("Frame_VideoFrame")
        self.Frame_VideoCtrlBar = QtWidgets.QFrame(self.Frame_VideoFrame)
        self.Frame_VideoCtrlBar.setGeometry(QtCore.QRect(0, 680, 881, 91))
        self.Frame_VideoCtrlBar.setStyleSheet("\n"
"background-color: rgb(64, 225, 199);")
        self.Frame_VideoCtrlBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_VideoCtrlBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_VideoCtrlBar.setObjectName("Frame_VideoCtrlBar")
        self.Button_NextPic = QtWidgets.QPushButton(self.Frame_VideoCtrlBar)
        self.Button_NextPic.setGeometry(QtCore.QRect(80, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.Button_NextPic.setFont(font)
        self.Button_NextPic.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(93, 255, 215);\n"
"border-radius:35px;\n"
"border:2px groove gray;\n"
"border-style:outset\n"
"}\n"
"")
        self.Button_NextPic.setObjectName("Button_NextPic")
        self.Button_PrePic = QtWidgets.QPushButton(self.Frame_VideoCtrlBar)
        self.Button_PrePic.setGeometry(QtCore.QRect(160, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.Button_PrePic.setFont(font)
        self.Button_PrePic.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(93, 255, 215);\n"
"border-radius:35px;\n"
"border:2px groove gray;\n"
"border-style:outset\n"
"}\n"
"")
        self.Button_PrePic.setObjectName("Button_PrePic")
        self.Frame_VideoInfo = QtWidgets.QFrame(self.Frame_VideoCtrlBar)
        self.Frame_VideoInfo.setGeometry(QtCore.QRect(520, 10, 341, 71))
        self.Frame_VideoInfo.setStyleSheet("background-color: rgb(96, 102, 191);")
        self.Frame_VideoInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_VideoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_VideoInfo.setObjectName("Frame_VideoInfo")
        self.Button_NextObject = QtWidgets.QPushButton(self.Frame_VideoCtrlBar)
        self.Button_NextObject.setGeometry(QtCore.QRect(290, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.Button_NextObject.setFont(font)
        self.Button_NextObject.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(93, 255, 215);\n"
"border-radius:35px;\n"
"border:2px groove gray;\n"
"border-style:outset\n"
"}\n"
"")
        self.Button_NextObject.setObjectName("Button_NextObject")
        self.Button_PreObject = QtWidgets.QPushButton(self.Frame_VideoCtrlBar)
        self.Button_PreObject.setGeometry(QtCore.QRect(380, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.Button_PreObject.setFont(font)
        self.Button_PreObject.setStyleSheet("QPushButton\n"
"{\n"
"background-color: rgb(93, 255, 215);\n"
"border-radius:35px;\n"
"border:2px groove gray;\n"
"border-style:outset\n"
"}\n"
"")
        self.Button_PreObject.setObjectName("Button_PreObject")
        self.label = QtWidgets.QLabel(self.Frame_VideoFrame)
        self.label.setGeometry(QtCore.QRect(410, 320, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/icon_camera.png"))
        self.label.setObjectName("label")
        self.Lable_VideoTitle = QtWidgets.QLabel(self.Frame_VideoFrame)
        self.Lable_VideoTitle.setGeometry(QtCore.QRect(30, 20, 180, 78))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Lable_VideoTitle.setFont(font)
        self.Lable_VideoTitle.setObjectName("Lable_VideoTitle")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_ShotOne.setText(_translate("MainWindow", "逐件扫描"))
        self.Button_ShotStop.setText(_translate("MainWindow", "停止扫描"))
        self.Button_Settings.setText(_translate("MainWindow", "设置"))
        self.Button_ShotBegin.setText(_translate("MainWindow", "开始扫描"))
        self.Button_Quit.setText(_translate("MainWindow", "退出"))
        self.label_2.setText(_translate("MainWindow", "操作"))
        self.Button_NextPic.setText(_translate("MainWindow", "下一帧"))
        self.Button_PrePic.setText(_translate("MainWindow", "上一帧"))
        self.Button_NextObject.setText(_translate("MainWindow", "下一件"))
        self.Button_PreObject.setText(_translate("MainWindow", "上一件"))
        self.Lable_VideoTitle.setText(_translate("MainWindow", "温度分布显示"))
import img_rc
